networks:
  perf-testing-net:
    driver: bridge

services:
  target-app:
    build:
      context: ./target-app
    container_name: target-app
    ports:
      - "5001:5000"
    networks:
      - perf-testing-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}

  locust-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locust-master
    ports:
      - "8089:8089"  # Locust Web UI
      - "5557:5557"  # Port for worker communication
      - "5558:5558"  # Port for worker communication
    volumes:
      - ./locustfiles/scenarios:/mnt/locust
    networks:
      - perf-testing-net
    command: ["locust", "-f", "/mnt/locust/simple_load.py", "--master", "--host=http://target-app:5000", "--web-port", "8089"]
    depends_on:
      target-app:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8089/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  locust-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./locustfiles/scenarios:/mnt/locust
    networks:
      - perf-testing-net
    command: ["locust", "-f", "/mnt/locust/simple_load.py", "--worker", "--master-host", "locust-master"]
    depends_on:
      - locust-master

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./grafana/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    networks:
      - perf-testing-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    depends_on:
      locust-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - perf-testing-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  prometheus_data:
  grafana_data:
