global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Target application metrics (includes health status)
  - job_name: 'target-app-metrics'
    static_configs:
      - targets: ['target-app:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
