notifiers:
  - name: email-alerts
    type: email
    uid: email-alerts
    orgId: 1
    isDefault: true
    sendReminder: true
    disableResolveMessage: false
    frequency: 10m
    settings:
      addresses: "admin@example.com"
      subject: "Grafana Alert - {{ .GroupLabels.SortedPairs }}"
      
  - name: webhook-alerts
    type: webhook
    uid: webhook-alerts
    orgId: 1
    isDefault: false
    sendReminder: false
    disableResolveMessage: false
    frequency: 10m
    settings:
      url: "http://localhost:3000/api/webhooks/alert"
      httpMethod: "POST"
      username: ""
      password: ""
